theme: jekyll-theme-midnight
title: zkMove
description: a scalable smart contract runtime environment that combines Move, the most secure programming language, with PLONK, a maturing zero-knowledge proof technology
